apiVersion: v1
kind: Secret
metadata:
  name: terzo-secrets
  namespace: terzo
type: Opaque
stringData:
  JWT_SECRET: "terzocloud_jwt_secret_2025_change_me_in_prod"
  ENCRYPT_KEY: "terzocloud_encrypt_key_2025_change_me"
  MONGO_URI: "mongodb://mongo-0.mongo-headless.terzo.svc.cluster.local:27017/terzocloud_assets"
