/**
 * seed/users.seed.js
 * Seeds 91 employees from the Terzo Employees List.
 * reportingManager stores only "First Last" so the UI dropdown resolves correctly.
 * Runs on every server start — upserts so existing records are kept up to date.
 */
const User = require('../db/models/User');
const bcrypt = require('bcryptjs');

const EMPLOYEES = [
  {
    empId: "E001",
    first: "Brandon",
    last: "Card",
    email: "bcard@terzocloud.com",
    jobTitle: "Chief Executive Officer",
    reportingManager: "",
    dept: "Executive",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Admin",
    status: 'Active',
  },
  {
    empId: "E003",
    first: "Pradeep",
    last: "Thangavel",
    email: "pradeep@terzocloud.com",
    jobTitle: "Executive Vice President (India)",
    reportingManager: "Zeyad Rajabi",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-05-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E004",
    first: "Mohanraja",
    last: "Ranganathan",
    email: "mohan@terzocloud.com",
    jobTitle: "Senior Principal Engineer",
    reportingManager: "Pradeep Thangavel",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2020-10-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E005",
    first: "Gowtham",
    last: "Manohar",
    email: "gowtham@terzocloud.com",
    jobTitle: "AI Operations Manager",
    reportingManager: "Kevin Character",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2020-10-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E006",
    first: "Gowtham",
    last: "Veerappan",
    email: "gowthamv@terzocloud.com",
    jobTitle: "Staff Software Engineer",
    reportingManager: "Ragav R",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2020-10-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E007",
    first: "Dinesh",
    last: "Baskaran",
    email: "dinesh@terzocloud.com",
    jobTitle: "Staff Software Engineer",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2020-10-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E008",
    first: "Brad",
    last: "Grabowski",
    email: "bradg@terzocloud.com",
    jobTitle: "Director of Product Design",
    reportingManager: "Zeyad Rajabi",
    dept: "Product",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E012",
    first: "Ragav",
    last: "R",
    email: "ragav@terzocloud.com",
    jobTitle: "Director of Engineering",
    reportingManager: "Kevin Redwine",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2020-10-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E014",
    first: "Yogesh",
    last: "Selvakumaran",
    email: "yogesh@terzocloud.com",
    jobTitle: "Manager - AI Services, India Lead",
    reportingManager: "Griffin Rutstein",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-01-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E016",
    first: "Spencer",
    last: "Ross",
    email: "sross@terzocloud.com",
    jobTitle: "Director of Global Sales",
    reportingManager: "Brandon Card",
    dept: "Sales",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E019",
    first: "Vinotha",
    last: "Senthilkumaran",
    email: "vinotha@terzocloud.com",
    jobTitle: "Senior Software Engineer",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-04-16'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E020",
    first: "Paventhan",
    last: "PKP",
    email: "paventhan@terzocloud.com",
    jobTitle: "Senior Manager",
    reportingManager: "Pradeep Thangavel",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-05-03'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E022",
    first: "Vasanth",
    last: "Pandian",
    email: "vp@terzocloud.com",
    jobTitle: "Director of Engineering",
    reportingManager: "Pradeep Thangavel",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-05-07'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E025",
    first: "Michail",
    last: "Angarsky",
    email: "michael.angarsky@terzocloud.com",
    jobTitle: "General Counsel and Head of HR",
    reportingManager: "Brandon Card",
    dept: "Legal",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E026",
    first: "Griffin",
    last: "Rutstein",
    email: "griffin@terzocloud.com",
    jobTitle: "Head of Global AI Services",
    reportingManager: "Kevin Character",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E029",
    first: "Harish",
    last: "VC Chandrasekar",
    email: "harish@terzocloud.com",
    jobTitle: "India, General Manager & Head of Customer Support",
    reportingManager: "Matt Hines",
    dept: "Operations",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-07-26'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E030",
    first: "Kevin",
    last: "Redwine",
    email: "kredwine@terzocloud.com",
    jobTitle: "Chief Data Science Officer",
    reportingManager: "Eric Pritchett",
    dept: "Executive",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Admin",
    status: 'Active',
  },
  {
    empId: "E032",
    first: "Ajay",
    last: "Christopher Hubert",
    email: "ajay@terzocloud.com",
    jobTitle: "Staff Software Engineer",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-09-22'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E033",
    first: "Hariharan",
    last: "Vaithianathan",
    email: "hariharan@terzocloud.com",
    jobTitle: "Lead Software Engineer",
    reportingManager: "Philippe Grangier",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-10-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E034",
    first: "Vincent",
    last: "Halle",
    email: "vincent@terzocloud.com",
    jobTitle: "Director of Development",
    reportingManager: "Kevin Redwine",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E035",
    first: "Prasannakumar",
    last: "Vijayakumar",
    email: "prasanna@terzocloud.com",
    jobTitle: "Senior Software Engineer",
    reportingManager: "Paventhan PKP",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-10-04'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E036",
    first: "Divya",
    last: "Murugeson",
    email: "divya@terzocloud.com",
    jobTitle: "Senior Software Engineer",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-10-18'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E039",
    first: "Sowmiya",
    last: "Sakthivel",
    email: "sowmiya@terzocloud.com",
    jobTitle: "Senior Software Engineer",
    reportingManager: "Paventhan PKP",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-11-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E043",
    first: "Iyyappan",
    last: "Moorthy",
    email: "iyyappan@terzocloud.com",
    jobTitle: "Staff Software Engineer",
    reportingManager: "Ragav R",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-03-23'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E047",
    first: "Ahamed",
    last: "Riyas",
    email: "ahamed@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Ragav R",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-06-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E048",
    first: "Ananya",
    last: "Mani",
    email: "ananya@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Ragav R",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-06-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E050",
    first: "Mohanamala",
    last: "Mariappan",
    email: "mohanamala@terzocloud.com",
    jobTitle: "Staff Software Engineer",
    reportingManager: "Ragav R",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2021-06-28'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E051",
    first: "Divya",
    last: "Rajavel",
    email: "divyar@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-06-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E052",
    first: "Karthi",
    last: "Selvam",
    email: "karthi@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-06-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E053",
    first: "Kavipriya",
    last: "Swaminathan",
    email: "kavipriya@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-06-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E058",
    first: "Dhanusha",
    last: "Arumugam",
    email: "dhanusha.a@terzocloud.com",
    jobTitle: "Lead Analyst (IN)",
    reportingManager: "Yogesh Selvakumaran",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-08-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E059",
    first: "Shunmugavel",
    last: "Subramanian",
    email: "shunmugavel@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Ragav R",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-09-16'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E061",
    first: "Nivetha",
    last: "Palanisamy",
    email: "nivetha@terzocloud.com",
    jobTitle: "Senior Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-11-07'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E063",
    first: "Himalaya",
    last: "Kachhawaha",
    email: "himalaya@terzocloud.com",
    jobTitle: "Product Manager",
    reportingManager: "Brad Grabowski",
    dept: "Product",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2023-04-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E064",
    first: "Kristen",
    last: "Pritchett",
    email: "kristenp@terzocloud.com",
    jobTitle: "Manager, Human Resources",
    reportingManager: "Michail Angarsky",
    dept: "Human Resources",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E065",
    first: "Karthick",
    last: "Ramesh",
    email: "karthick@terzocloud.com",
    jobTitle: "Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2023-04-21'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E068",
    first: "Dineshkumar",
    last: "Varadharajan",
    email: "dinesh.v@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2024-01-08'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E076",
    first: "Kavimitraa",
    last: "Mohan",
    email: "kavimitraa@terzocloud.com",
    jobTitle: "Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2024-06-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E078",
    first: "Harshini",
    last: "Thiru",
    email: "harshni@terzocloud.com",
    jobTitle: "Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2024-06-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E079",
    first: "Aswini",
    last: "Mathiyazhagan",
    email: "aswini@terzocloud.com",
    jobTitle: "Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2024-06-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E080",
    first: "Dharshini",
    last: "Thambikalaiyan",
    email: "dharshini@terzocloud.com",
    jobTitle: "Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2024-06-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "E081",
    first: "Priyadharshini",
    last: "Manoharan",
    email: "priyadharshini@terzocloud.com",
    jobTitle: "Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2024-06-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Andrew",
    last: "Forbes",
    email: "andrew@terzocloud.com",
    jobTitle: "Manager, Data Strategy (CAN)",
    reportingManager: "Griffin Rutstein",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Anna",
    last: "Gurvits",
    email: "anna@terzocloud.com",
    jobTitle: "Integrated Marketing Manager",
    reportingManager: "Heather Silverman",
    dept: "Marketing",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Ashlee",
    last: "Vargas",
    email: "av@terzocloud.com",
    jobTitle: "Executive Assistant to the CEO",
    reportingManager: "Brandon Card",
    dept: "Executive Administration",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Brody",
    last: "Elkins",
    email: "belkins@terzocloud.com",
    jobTitle: "Account Executive",
    reportingManager: "Brandon Card",
    dept: "Sales",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Caelan",
    last: "Seto",
    email: "cseto@terzocloud.com",
    jobTitle: "Associate Software Developer",
    reportingManager: "Kevin Redwine",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Daniela",
    last: "Nash",
    email: "daniela@terzocloud.com",
    jobTitle: "Data Analyst (CAN)",
    reportingManager: "Stephanie Yaacoub",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Feroz",
    last: "Mudupully",
    email: "ferozkhan@terzocloud.com",
    jobTitle: "Engagement Director",
    reportingManager: "Kevin Character",
    dept: "Customer Operations",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Heather",
    last: "Silverman",
    email: "hsilverman@terzocloud.com",
    jobTitle: "Vice President of Marketing and Communications",
    reportingManager: "Brandon Card",
    dept: "Marketing",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Jason",
    last: "Anderman",
    email: "janderman@terzocloud.com",
    jobTitle: "Deputy General Counsel",
    reportingManager: "Michail Angarsky",
    dept: "Legal",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "JP",
    last: "Giraldo Ramirez",
    email: "juanpablo@terzocloud.com",
    jobTitle: "Data Analyst",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Justin",
    last: "Adams",
    email: "justin.a@terzocloud.com",
    jobTitle: "Data Analyst",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Kade",
    last: "Manuel",
    email: "kade@terzocloud.com",
    jobTitle: "Customer Support Manager",
    reportingManager: "Kevin Character",
    dept: "Customer Operations",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Ken",
    last: "Calder",
    email: "kcalder@terzocloud.com",
    jobTitle: "Senior Full Stack Developer",
    reportingManager: "Kevin Redwine",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Kevin",
    last: "Character",
    email: "kcharacter@terzocloud.com",
    jobTitle: "Vice President, Customer Operations",
    reportingManager: "Eric Pritchett",
    dept: "Customer Operations",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Kieran",
    last: "Murphy",
    email: "kieran@terzocloud.com",
    jobTitle: "Creative Director",
    reportingManager: "Heather Silverman",
    dept: "Marketing",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Kioaka",
    last: "Bynum",
    email: "kbynum@terzocloud.com",
    jobTitle: "Manager, AI Services (US)",
    reportingManager: "Griffin Rutstein",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Leo",
    last: "Deepak",
    email: "leo@terzocloud.com",
    jobTitle: "Senior Data Analyst (IN)",
    reportingManager: "Dhanusha Arumugam",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2023-04-21'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Lindsey",
    last: "Still",
    email: "lindsey@terzocloud.com",
    jobTitle: "Data Analyst II",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Luc",
    last: "Belanger",
    email: "luc.belanger@terzocloud.com",
    jobTitle: "Principal Applied Science",
    reportingManager: "Philippe Grangier",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Lucia",
    last: "Steiner",
    email: "lucia@terzocloud.com",
    jobTitle: "Data Analyst (CAN)",
    reportingManager: "Stephanie Yaacoub",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Luis",
    last: "Ocegueda",
    email: "luis@terzocloud.com",
    jobTitle: "Director of Engineering",
    reportingManager: "Zeyad Rajabi",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Luke",
    last: "Ashworth",
    email: "lashworth@terzocloud.com",
    jobTitle: "Engagement Manager II",
    reportingManager: "Kevin Character",
    dept: "Customer Operations",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Max",
    last: "Ferguson",
    email: "maxferguson@terzocloud.com",
    jobTitle: "Director of Strategic Partnerships",
    reportingManager: "Brandon Card",
    dept: "Sales",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Max",
    last: "Perlstein",
    email: "max@terzocloud.com",
    jobTitle: "Senior Data Analyst",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Maxime",
    last: "Jacques",
    email: "maxime@terzocloud.com",
    jobTitle: "Senior AI/ML Developer",
    reportingManager: "Kevin Redwine",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Melany",
    last: "Delgado",
    email: "melany@terzocloud.com",
    jobTitle: "Technical Program Manager",
    reportingManager: "Kevin Redwine",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Miaoyin",
    last: "Li",
    email: "miaoyin@terzocloud.com",
    jobTitle: "Data Analyst (CAN)",
    reportingManager: "Stephanie Yaacoub",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Mythilippriya",
    last: "Sankar",
    email: "mythilipriya@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Ragav R",
    dept: "Data Science - Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2022-06-06'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Natan",
    last: "Sakajiri",
    email: "natan@terzocloud.com",
    jobTitle: "Data Analyst (CAN)",
    reportingManager: "Stephanie Yaacoub",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Nicholas",
    last: "McGaughey",
    email: "nicholas@terzocloud.com",
    jobTitle: "Data Analyst",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Niranjan",
    last: "Rajendran",
    email: "niranjan@terzocloud.com",
    jobTitle: "Software Engineer III",
    reportingManager: "Vasanth Pandian",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2025-12-09'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Philippe",
    last: "Grangier",
    email: "philippe@terzocloud.com",
    jobTitle: "Director, Applied Science",
    reportingManager: "Kevin Redwine",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Revathi",
    last: "Sakthivel",
    email: "revathi@terzocloud.com",
    jobTitle: "Staff Engineer",
    reportingManager: "Ragav R",
    dept: "Engineering",
    employmentType: "Full Time",
    location: "India",
    joined: new Date('2026-01-05'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Ritu",
    last: "Patel",
    email: "ritu@terzocloud.com",
    jobTitle: "Data Analyst",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Sena",
    last: "Onen Oz",
    email: "sena@terzocloud.com",
    jobTitle: "Data Scientist",
    reportingManager: "Philippe Grangier",
    dept: "Data Science",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Stephanie",
    last: "Yaacoub",
    email: "stephanie@terzocloud.com",
    jobTitle: "Manager, AI Services (CAN LEAD)",
    reportingManager: "Griffin Rutstein",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Stephen",
    last: "Horn",
    email: "stephen@terzocloud.com",
    jobTitle: "Data Analyst II",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Tian",
    last: "Gao",
    email: "tian@terzocloud.com",
    jobTitle: "Data Analyst (CAN)",
    reportingManager: "Stephanie Yaacoub",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "Canada",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Zeyad",
    last: "Rajabi",
    email: "zeyad.r@terzocloud.com",
    jobTitle: "Chief Product Officer",
    reportingManager: "Eric Pritchett",
    dept: "Executive",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Admin",
    status: 'Active',
  },
  {
    empId: "",
    first: "Ryan",
    last: "Tanner",
    email: "rtanner@terzocloud.com",
    jobTitle: "Marketing-Designer",
    reportingManager: "",
    dept: "Marketing",
    employmentType: "Contractor",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Urvasi",
    last: "P",
    email: "urvasi@terzocloud.com",
    jobTitle: "Accounts Manager",
    reportingManager: "Harish VC Chandrasekar",
    dept: "India Accounts & HR",
    employmentType: "Contractor",
    location: "India",
    joined: new Date('2021-12-01'),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Praveen",
    last: "M",
    email: "praveen.m@terzocloud.com",
    jobTitle: "IT - Admin",
    reportingManager: "Vasanth Pandian",
    dept: "IT",
    employmentType: "Contractor",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Sameer",
    last: "Sharma",
    email: "sameer@terzocloud.com",
    jobTitle: "Engagement Director",
    reportingManager: "Kevin Character",
    dept: "Customer Operations",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Avinesh",
    last: "Bedi",
    email: "avinesh@terzocloud.com",
    jobTitle: "Engagement Associate",
    reportingManager: "Kevin Character",
    dept: "Customer Operations",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Edward",
    last: "Warszycki",
    email: "edward@terzocloud.com",
    jobTitle: "Director of Sales",
    reportingManager: "Brandon Card",
    dept: "Sales",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Parker",
    last: "Walrod",
    email: "parker@terzocloud.com",
    jobTitle: "Data Analyst",
    reportingManager: "Kioaka Bynum",
    dept: "AI Services",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Michael",
    last: "Deal",
    email: "michael@terzocloud.com",
    jobTitle: "Head of Finance",
    reportingManager: "Brandon Card",
    dept: "Account/Finance",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Eric",
    last: "Pritchett",
    email: "epritchett@terzocloud.com",
    jobTitle: "Chief Operations Officer",
    reportingManager: "",
    dept: "Executive",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  },
  {
    empId: "",
    first: "Matt",
    last: "Hines",
    email: "matt.hines@terzocloud.com",
    jobTitle: "Corporate Controller",
    reportingManager: "",
    dept: "Finance",
    employmentType: "Full Time",
    location: "USA",
    joined: new Date(),
    role: "Staff",
    status: 'Active',
  }
];

async function seedUsers() {
  try {
    const defaultHash = await bcrypt.hash('Terzo@2025', 10);
    let created = 0, skipped = 0;
    for (const emp of EMPLOYEES) {
      const { email, ...rest } = emp;
      const existing = await User.findOne({ email });
      if (existing) {
        skipped++;
      } else {
        await User.create({ email, ...rest, password: defaultHash });
        created++;
      }
    }
    console.log(`👥  Users seeded — ${created} created, ${skipped} skipped (existing preserved)`);
  } catch (err) {
    console.error('❌  User seed failed:', err.message);
  }
}

module.exports = { seedUsers };
